### PR TITLE
support GITHUB_TOKEN environment variable

### PR DESCRIPTION
**Pull request by jlevon**
Signed-off-by: John Levon <john.levon@nutanix.com>

### CODE REVIEW

**Review by danmcd — COMMENTED** [review]
Dumb question, does processing GITHUB_TOKEN first increase, or decrease, the surprise level? If someone has GITHUB_API_TOKEN_FILE *and* GITHUB_TOKEN, post-this-change the GITHUB_TOKEN will take precedence.  That might be a net improvement, but I don't have enough experience here to speak to that.

**Comment by jlevon** [comment]
Generally env vars over-ride files, as a rule. But it's also worth noting GITHUB_TOKEN is a semi-standard, so if it's set, it's likely to work. But hea.

**Review by danmcd — APPROVED** [review]
Okay, GITHUB_TOKEN working first appears to be the least-surprise from what you say.  I can deal with that.

**Comment by danmcd** [comment]
(Pardon Actually-*-by lines... another repo gave the wrong author credit today, so I was being paranoid.)

**Comment by jlevon** [comment]
Thanks!

**Pull request merged**
